SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [ADMISION].[TBL_VW_FT_ADMISION_ESP_ORD] AS 
SELECT-- count(*)--TOP 100
		PE.COD_SOLIC_INGR,
		PE.RUT,
		0 CLAVE_NACIONAL,
		PE.COD_CURRICULUM,
		PE.ANO_ADMIS,
		PE.COD_PERIODO AS COD_PERIODO_B,
		CASE WHEN PE.COD_PERIODO = 21 THEN PE.ANO_ADMIS*100+1
		ELSE PE.ANO_ADMIS*100+2 END AS COD_PERIODO,
		0 PREF,
		PE.PUESTO,
		PE.PRIORID,
		PE.PTJE_PACE,
		PE.PTJE_POND_SELEC,
		CAST(PE.PTJE_SELEC as float) PTJE_SELEC,
		'0' COD_SIT_POSTULACION,
		'0' NOM_SITUACION_POSTULACION,
		'0' COD_SITUACION_POSTULACION_INICIAL,
		'0' NOM_SITUACION_POSTULACION_INICIAL,
		PE.COD_ESTADO_POSTULACION,
		VI.COD_VIA_ADMIS COD_VIA_ADMIS, 
		PE.COD_CASO_ADMIS, --NO EXISTE SOLO SE AGREGA PARA RELLENAR
		VI.NOM_VIA_ADMIS AS VIA_ADMISION, 
		VI2.NOM_CASO_ADMIS AS CASO_ADMISION,
		PTJE1.NEM,
		PTJE1.RKG,
		PTJE1.CIE,
		PTJE1.HYC,
		PTJE1.LYC,
		PTJE1.MAT,
		PTJE1.PSU,
		PTJE1.PCMLT,
		AAD.PROM_NOTA_ENSEN_MEDIA,
		AAD.PROM_PAA,
		AAD.COD_COLEGIO,
		AAD.ANO_EGRESO_COLEGIO,
		AAD.ANO_COLEGIO,
		AAD.BECA_EXCELENCIA_ACADEM,
		AAD.PACE
	

	--count(*)

	--SELECT TOP 100 *
	FROM 
		ADMISION.SOLIC_INGR_HIST PE
	LEFT OUTER JOIN
	ADMISION.VIA_ADMIS_HIST VI
	on
	( PE.COD_VIA_ADMIS = VI.COD_VIA_ADMIS)
	LEFT OUTER JOIN
	ADMISION.CASO_ADMIS_HIST VI2
	on
	( PE.COD_CASO_ADMIS = VI2.COD_CASO_ADMIS)
	
	LEFT OUTER JOIN 
			(SELECT 
		RUT,
		ANO_ADMIS,
		MAX(CIE) AS CIE, 
		MAX(HYC) AS HYC,
		MAX(LYC) AS LYC,
		MAX(MAT) AS MAT,
		MAX(NEM) AS NEM, 
		MAX(PSU) AS PSU,
		MAX(PCMLT) AS PCMLT,
		MAX(RKG) AS RKG

		FROM
			[ADMISION].[PTJE_ADMISION] PT
		WHERE ANO_ADMIS > 2007
		GROUP BY 
		RUT,
		ANO_ADMIS ) as PTJE1
	ON
		(PE.RUT =PTJE1.RUT AND PE.ANO_ADMIS = PTJE1.ANO_ADMIS)
	
	LEFT OUTER JOIN
		(SELECT 
			RUT,
			ANO_ADMIS,
			PROM_NOTA_ENSEN_MEDIA,
			PROM_PAA,
			COD_COLEGIO,
			ANO_EGRESO_COLEGIO,
			ANO_COLEGIO,
			BECA_EXCELENCIA_ACADEM,
			PACE

		FROM 
			ADMISION.ANTECED_ADMIS_HIST ) AAD
	ON
		(PE.RUT = AAD.RUT AND PE.ANO_ADMIS = AAD.ANO_ADMIS)

	--LEFT OUTER JOIN 
	--SELECT * FROM 
		--ADM.ESTADO_POSTULACION

	WHERE 
		PE.ANO_ADMIS > 2008 

	
UNION ALL


SELECT 
		PE.COD_POSTULACION_EFECT COD_SOLIC_INGR ,
		PE.RUT,
		PE.CLAVE_NACIONAL,
		PE.COD_CURRICULUM,
		PE.ANO_ADMIS,
		PE.COD_PERIODO AS COD_PERIODO_B,
		CASE WHEN PE.COD_PERIODO = 21 THEN PE.ANO_ADMIS*100+1
		ELSE PE.ANO_ADMIS*100+2 END AS COD_PERIODO,
		PE.PREF,
		PE.PUESTO,
		0 PRIORID,
		'0' PTJE_PACE,
		0 PTJE_POND_SELEC,
		PE.PTJE_SELEC,
		PE.COD_SIT_POSTULACION, -- CUANDO NO ES SELECCIONADO
		ST1.NOM_SIT_POSTULACION AS NOM_SITUACION_POSTULACION,
		PE.COD_SIT_POSTULACION_INICIAL AS COD_SIT_POSTULACION_INICIAL,
		ST2.NOM_SIT_POSTULACION AS NOM_SITUACION_POSTULACION_INICIAL,
		0 COD_ESTADO_POSTULACION, 
		600 COD_VIA_ADMIS, --NO EXISTE ESTA COLUMNA PERO SE NECESITA
		601 COD_CASO_ADMIS, --NO EXISTE SOLO SE AGREGA PARA RELLENAR
		VI.NOM_VIA_ADMIS AS VIA_ADMISION, 
		VI.NOM_CASO_ADMIS AS CASO_ADMISION,
		PTJE1.NEM,
		PTJE1.RKG,
		PTJE2.CIE,
		PTJE2.HYC,
		PTJE2.LYC,
		PTJE2.MAT,
		PTJE2.PSU,
		PTJE2.PCMLT,
		AAD.PROM_NOTA_ENSEN_MEDIA,
		AAD.PROM_PAA,
		AAD.COD_COLEGIO,
		AAD.ANO_EGRESO_COLEGIO,
		AAD.ANO_COLEGIO,
		AAD.BECA_EXCELENCIA_ACADEM,
		AAD.PACE
	

	--count(*)
	FROM 
		ADMISION.POSTULACION_EFECT_HIST PE
	LEFT OUTER JOIN
	(
		SELECT 
			VIA.COD_VIA_ADMIS,
			VIA.NOM_VIA_ADMIS,
			CAS.COD_CASO_ADMIS,
			CASE 
			WHEN CAS.NOM_CASO_ADMIS IS NULL THEN 'PSU'
			ELSE CAS.NOM_CASO_ADMIS END AS NOM_CASO_ADMIS
		FROM 
			ADMISION.CASO_ADMIS_HIST CAS
		FULL OUTER JOIN 
			ADMISION.VIA_ADMIS_HIST VIA
		ON
			(CAS.COD_VIA_ADMIS = VIA.COD_VIA_ADMIS)
	) AS VI
	ON  
		(600 = VI.COD_VIA_ADMIS)
	LEFT OUTER JOIN
		ADMISION.SIT_POSTULACION_HIST  ST1
	ON
		(PE.COD_SIT_POSTULACION = ST1.COD_SIT_POSTULACION)
	LEFT OUTER JOIN
		ADMISION.SIT_POSTULACION_HIST  ST2
	ON
		(PE.COD_SIT_POSTULACION_INICIAL = ST2.COD_SIT_POSTULACION)

	LEFT OUTER JOIN 
			(SELECT 
		RUT,
		ANO_ADMIS,
		MAX(CIE) AS CIE, 
		MAX(HYC) AS HYC,
		MAX(LYC) AS LYC,
		MAX(MAT) AS MAT,
		MAX(NEM) AS NEM, 
		MAX(PSU) AS PSU,
		MAX(PCMLT) AS PCMLT,
		MAX(RKG) AS RKG

		FROM
			[ADMISION].[PTJE_ADMISION] PT
		WHERE ANO_ADMIS > 2008
		GROUP BY 
		RUT,
		ANO_ADMIS ) as PTJE1
	ON
		(PE.RUT =PTJE1.RUT AND PE.ANO_POND = PTJE1.ANO_ADMIS)
	LEFT OUTER JOIN 
			(SELECT 
		RUT,
		ANO_ADMIS,
		MAX(CIE) AS CIE, 
		MAX(HYC) AS HYC,
		MAX(LYC) AS LYC,
		MAX(MAT) AS MAT,
		MAX(NEM) AS NEM, 
		MAX(PSU) AS PSU,
		MAX(PCMLT) AS PCMLT,
		MAX(RKG) AS RKG

		FROM
			[ADMISION].[PTJE_ADMISION] PT
		WHERE ANO_ADMIS > 2007
		GROUP BY 
		RUT,
		ANO_ADMIS )  as PTJE2
	ON
		(PE.RUT =PTJE2.RUT AND PE.ANO_ADMIS = PTJE2.ANO_ADMIS)
	LEFT OUTER JOIN
		(SELECT 
			RUT,
			ANO_ADMIS,
			PROM_NOTA_ENSEN_MEDIA,
			PROM_PAA,
			COD_COLEGIO,
			ANO_EGRESO_COLEGIO,
			ANO_COLEGIO,
			BECA_EXCELENCIA_ACADEM,
			PACE

		FROM 
			ADMISION.ANTECED_ADMIS_HIST ) AAD
	ON
		(PE.RUT = AAD.RUT AND PE.ANO_ADMIS = AAD.ANO_ADMIS)

	WHERE 
		PE.ANO_ADMIS > 2008

	 

GO
