
select top 10 * from SC.STUDENT_360

select * from UTILS.ViewTablesUsage() where schema_name = 'SC' and view_name = 'STUDENT_360'

/*
ACADEMIC_DEGREE
ACADEMIC_LEVEL
ACADEMIC_PROGRAM
ACADEMIC_UNIT
ADMISSION_TYPE
COURSE
ENROLLMENT
ENROLLMENT_BY_TERM
FACULTY
GRADE
PERSON
SCHOOL_FINANCING_TYPE
SECONDARY_EDUCATION_INSTITUTION
SECTION
SECTION_REGISTRATION_TYPE
STUDENT
STUDENT_GRADUATES_FROM_SCHOOL
STUDENT_REGISTERS_SECTION
STUDENT_SPECIAL_STATUS
STUDENT_TAGS
STUDENT_TAGS_BY_TERM
STUDENT_VALIDITY_TYPE
STUDENT_WITH_CHILDREN
TERM
*/