/* VISTA TBL_VW_FT_ADM_VAC_CASO */
/*
ADMISION	CASO_ADMIS_HIST
ADMISION	HIST_CARRERA_HIST
ADMISION	TBL_VW_FT_ADMISION_ESP_ORD
ADMISION	VAC_CASO_CURRICULUM
ADMISION	VIA_ADMIS_HIST
*/

select top 4 * from ADMISION.TBL_VW_FT_ADM_VAC_CASO

-- Se puede reapuntar sin problemas a ADMISION.CASO_ADMIS
select top 4 * from ADMISION.CASO_ADMIS_HIST
select count(1) from ADMISION.CASO_ADMIS_HIST --53
select top 4 * from ADMISION.CASO_ADMIS
select count(1) from ADMISION.CASO_ADMIS      --54

-- Se puede reapuntar sin problemas a ADMISION.HIST_CARRERA
select top 4 * from ADMISION.HIST_CARRERA_HIST
select count(1) from ADMISION.HIST_CARRERA_HIST   -- 32925
select top 4 * from ADMISION.HIST_CARRERA
select count(1) from ADMISION.HIST_CARRERA        -- 32917

select top 4 * from ADMISION.TBL_VW_FT_ADMISION_ESP_ORD_PAS WHERE NEM IS NOT NULL
select top 4 * from ADMISION.TBL_VW_FT_ADMISION_ESP_ORD

select top 4
    A.COD_CURRICULUM,
	A.ANO_ADMIS, 
	A.COD_PERIODO_B,
	A.COD_PERIODO, 
	A.COD_CASO_ADMIS,
	A.COD_VIA_ADMIS,
	A.NOM_CASO_ADMIS,
	A.NOM_VIA_ADMIS
from ADMISION.TBL_VW_FT_ADMISION_ESP_ORD_PAS as A

-- Se puede reapuntar sin problemas a ADMISION.VIA_ADMIS_HIST
select top 4 * from ADMISION.VIA_ADMIS_HIST
select top 4 * from ADMISION.VIA_ADMIS
select count(1) from ADMISION.VIA_ADMIS_HIST -- 7
select count(1) from ADMISION.VIA_ADMIS      -- 7

/* TBL_VW_FT_ADM_VAC_VIA */

SELECT * 
FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE 
WHERE VIEW_NAME = 'TBL_VW_FT_ADM_VAC_VIA'

/*
HIST_CARRERA_HIST
TBL_VW_FT_ADMISION_ESP_ORD
VAC_CASO_CURRICULUM
VAC_VIA_CURRICULUM
*/

select top 4 * from ADMISION.TBL_VW_FT_ADM_VAC_VIA

/* TBL_VW_FT_ADMISION_ESP_ORD_PAS */

SELECT * 
FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE 
WHERE VIEW_NAME = 'TBL_VW_FT_ADMISION_ESP_ORD_PAS'

/*
ANTECED_ADMIS_HIST
CASO_ADMIS_HIST
PERS_ADMIS_HIST
POSTULACION_EFECT_HIST
PTJE_ADMISION
SIT_POSTULACION_HIST
SOLIC_INGR_HIST
VIA_ADMIS_HIST
*/

UPDATE SBX.CARGA_TABLA_STG_A_SBX 
SET FLG_SBX = 1
WHERE NOMBRE_OWNER = 'ADMISION'
AND NOMBRE_TABLA = 'PERS_ADMIS'

SELECT * FROM SBX.CARGA_TABLA_STG_A_SBX WHERE FLG_SBX = 1

-- go
select top 4 * from ADMISION.ANTECED_ADMIS_HIST
select top 4 * from ADMISION.ANTECED_ADMIS
select count(1) from ADMISION.ANTECED_ADMIS_HIST -- 445665
select count(1) from ADMISION.ANTECED_ADMIS      -- 459572

-- go
select top 4 * from ADMISION.CASO_ADMIS_HIST
select top 4 * from ADMISION.CASO_ADMIS
select count(1) from ADMISION.CASO_ADMIS_HIST  -- 53
select count(1) from ADMISION.CASO_ADMIS       -- 54

--danger
select top 4 * from ADMISION.PERS_ADMIS_HIST
select top 4 * from ADMISION.PERS_ADMIS
select count(1) from ADMISION.PERS_ADMIS_HIST  -- 417152
select count(1) from ADMISION.PERS_ADMIS       -- 428642

-- go
select top 4 * from ADMISION.POSTULACION_EFECT_HIST
select top 4 * from ADMISION.POSTULACION_EFECT
select count(1) from ADMISION.POSTULACION_EFECT_HIST  -- 355646
select count(1) from ADMISION.POSTULACION_EFECT       -- 355648

-- go
select top 4 * from ADMISION.SIT_POSTULACION_HIST
select top 4 * from ADMISION.SIT_POSTULACION
select count(1) from ADMISION.SIT_POSTULACION_HIST
select count(1) from ADMISION.SIT_POSTULACION

-- problems
select top 4 * from ADMISION.SOLIC_INGR_HIST
select top 4 * from ADMISION.SOLIC_INGR
select count(1) from ADMISION.SOLIC_INGR_HIST  -- 202198
select count(1) from ADMISION.SOLIC_INGR       -- 5245

-- go
select top 4 * from ADMISION.VIA_ADMIS_HIST
select top 4 * from ADMISION.VIA_ADMIS
select count(1) from ADMISION.VIA_ADMIS_HIST
select count(1) from ADMISION.VIA_ADMIS

/* TBL_VW_FT_ADMISION_PAS */
SELECT * 
FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE 
WHERE VIEW_NAME = 'TBL_VW_FT_ADMISION_PAS'

/*
POSTULACION_EFECT_HIST --OK para reapuntar
SIT_POSTULACION_HIST   --OK para reapuntar
ANTECED_ADMIS_HIST     --OK para reapuntar
*/

-- REVISAR CURCE CON TABLA POSTUL
select top 4 * from ADMISION.TBL_VW_FT_ADMISION_PAS WHERE IVE_COLEGIO is not null
select count(1) from ADMISION.TBL_VW_FT_ADMISION_PAS